# Variables de directorios
SRC_PATH += $(shell pwd)/libraries/motorShield/src/
SOURCES  += $(wildcard $(shell pwd)/libraries/motorShield/src/*.c)
INC_PATH +=-I$(shell pwd)/libraries/motorShield/inc 

